@startuml
interface DataAccessObject<E, Id>{
        +{abstract}persistir(E e) : boolean
        +{abstract}actualizar(E e) : boolean
        +{abstract}eliminar(E e) : boolean
        +{abstract}buscarPorId(Id id) : E
        +{abstract}buscarPorRangos(offset : int, limite : int) : List<E>
        +{abstract}buscarTodos() : List<E>
        +{abstract}contar() : int
        +{abstract}cerrar() : void
    }
@enduml